### ISSUE TITLE
Problem with branches

### ISSUE THREAD

**Issue by matiasrebori** [nyakaz73/heroku-django-deploy#1]
Hi, i tried this github action and doesnt work for me, i think the problem is because github and heroku renamed the `master` branch to `main`. In the **main.yml** i changed the branch from `master`to `main`but when the action is running it tries to do **git push heroku master** when it has to be **git push heroku main** and throws the error: `src refspec master does not match any heroku`. I'm new to github so please let me know if anythings wrong.

**Comment by adriandavidauer** [comment]
Having the same issue! Description is pretty accurate :+1:

**Comment by adriandavidauer** [comment]
@matiasrebori I used this instead:
https://github.com/AkhileshNS/heroku-deploy#deploy-custom-branch
It worked for me. (You just need to change master to main in the *on:push:branches*)

**Comment by matiasrebori** [comment]
thanks for your help!
a question, should i close this issue?

**Comment by adriandavidauer** [comment]
I would leave the decision to @nyakaz73 
Maybe there is the plan to fix this in this action.

**Comment by matiasrebori** [comment]
ok, thanks.

**Comment by nyakaz73** [comment]
> Hi, i tried this github action and doesnt work for me, i think the problem is because github and heroku renamed the `master` branch to `main`. In the **main.yml** i changed the branch from `master`to `main`but when the action is running it tries to do **git push heroku master** when it has to be **git push heroku main** and throws the error: `src refspec master does not match any heroku`. I'm new to github so please let me know if anythings wrong.

Hello @matiasrebori this issue has been fixed on the latest  0.81. I have added a mandatory **git_branch** tag that lets you specify your default git branch you want to push from . eg master or main.

See example in the README  section. 
 Thanks for the feedback

**Comment by nyakaz73** [comment]
> I would leave the decision to @nyakaz73 Maybe there is the plan to fix this in this action.

Hello @adrianlubitz This issue have been fixed on the latest 0.81. I have added a mandatory git_branch tag that lets you specify your default git branch you want to push from . eg master or main.

See example in the README section.
Thanks for the feedback

**Comment by shivaylamba** [comment]
This still gives an error @nyakaz73

**Comment by nyakaz73** [comment]
> This still gives an error @nyakaz73

Kindly produce the steps to reproduce the error @shivaylamba

**Comment by nyakaz73** [comment]
> This still gives an error @nyakaz73
There is a mandatory git_branch tag that was put on v0.81
Make sure you specify the branch you want to push from eg
git_branch: main
